### ISSUE TITLE
Feature Request: public setColor method

### ISSUE THREAD

**Issue by bradmartin** [booncol/Pulsator4Droid#1]
Would be nice to have a programmatic  option to set the color. If I missed this already, apologies.

**Comment by DavidMont** [comment]
+1 on this

**Comment by DavidMont** [comment]
im waiting for my merge-request #3 commit: 9664061afec12d3c6fa79f5f1c57660d15c1f1ce

**Comment by DavidMont** [comment]
use mine if there isnt any updates on this `compile 'com.github.DavidMont:Pulsator4Droid:1.0.3'`

**Comment by booncol** [comment]
Added to version 1.0.3
