### ISSUE TITLE
Aninmation not showing

### ISSUE THREAD

**Issue by katchoua** [booncol/Pulsator4Droid#6]
Where am I supposed to place it in my layout file?

`<pl.bclogic.pulsator4droid.library.PulsatorLayout
                android:id="@+id/pulsator"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:pulse_count="4"
                app:pulse_duration="7000"
                app:pulse_repeat="0"
                app:pulse_color="@color/colorAccent"
                app:pulse_startFromScratch="false"
                app:pulse_interpolator="Linear">
                <Button
                    android:layout_width="match_parent"
                    android:layout_height="match_parent" />
            </pl.bclogic.pulsator4droid.library.PulsatorLayout>`

This is doesn't show.

**Comment by booncol** [comment]
You can place it in the root layout. To show animation call `start`.

```
PulsatorLayout pulsator = (PulsatorLayout) findViewById(R.id.pulsator);
pulsator.start();
```

**Comment by katchoua** [comment]
Thanks, I figured it out.
